Algoritmo "lista5questao11"
// Crie um programa que apresente o valor de uma potência de base qualquer (b).
// Elevada a um expoente qualquer (e), ou seja, de b^e.
Var
// Seção de Declarações das variáveis
// Não posso declarar a variável "e"
b, ex: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite um número para a base:")
leia(b)
Escreval("Digite um número para o expoente:")
leia(ex)

escreval(b," elevado à",ex," =",b^ex)

Fimalgoritmo