Algoritmo "lista5questao4"
// Desenvolver um programa que apresente o valor da soma dos 100 primeiros
// números inteiros (1+2+3+4...).

Var
// Seção de Declarações das variáveis 
acum, cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 1
acum <- 0
enquanto (cont <= 100) faca
         acum <- acum + cont
         escreval(acum)
         cont <- cont + 1
fimenquanto

Fimalgoritmo