Algoritmo "lista5questao8"
// Desenvolva um programa que apresente todos os ímpares na faixa de 0 a 20.

Var
// Seção de Declarações das variáveis
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
cont <- 0
escreval("Os ímpares de 0 até 20 são:")
enquanto cont <= 20 faca
         se cont%2 = 1 entao
            escreva(cont)
         fimse
         cont <- cont + 1
fimenquanto

Fimalgoritmo