Algoritmo "lista5questao7"
// Desenvolva um programa que apresente todos os divisíveis por 4 menores que
// 200. Se for, mestre, se não, pule.
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 1
enquanto cont <= 200 faca
         se cont%4 = 0 entao
            escreval(cont)
         fimse
cont <- cont + 1
         
fimenquanto

Fimalgoritmo