Algoritmo "lista4exercicio1"
// Peça um número. Informe se o número está acima ou abaixo de 1000.
Var
// Seção de Declarações das variáveis 
num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Informe um número: ")
leia(num)

se (num > 1000) entao
   escreva("O número é maior que 1000")
senao
     se (num < 1000) entao
        escreva("O número é menor que 1000")
     fimse
fimse

Fimalgoritmo