Algoritmo "lista5questao2"
// Desenvolva um programa que exiba os números em ordem decrescente de 100 a 1.

var
// Seção de Declarações das variáveis 
contador: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibindo os números de 100 a 1")
contador <- 100
enquanto (contador >= 1) faca
         escreval(contador)
         contador <- contador - 1
fimenquanto

Fimalgoritmo