Algoritmo "lista4exercicio5"
// Pergunte a singla de uma UF brasileira. E informe se o estado percente a
// a região sudeste.
Var
// Seção de Declarações das variáveis 
uf: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Informe a sigla do estado: ")
leia(uf)
se uf = "RJ" ou uf = "SP" ou uf = "MG" ou uf = "ES"
   escreva("O estado pertence a região sudeste)
senao
     escreva("O estado não percente a região sudeste")

Fimalgoritmo