Algoritmo "lista61q03"
// Desenvolver um programa que leia um vetor A 15 elementos, construa um vetor
// B de mesmo tipo, sendo que cada elemento do vetor B deve ser o fatorial do
// elemento correspondente do vetor A, apresentar o vetor B

Var
// Seção de Declarações das variáveis 
A: vetor[1..15] de inteiro
B: vetor[1..15] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo