Algoritmo "lista5questao13"
// Desenvolva um programa que imprima a tabuda de 3 a 6.

Var
// Seção de Declarações das variáveis 
fator1,fator2: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
fator1 <- 3
fator2 <- 1

enquanto fator1 <= 6 faca

   enquanto fator2 <= 10 faca
            escreval(fator1," x",fator2," =",fator1*fator2)
            fator2 <- fator2 + 1
   fimenquanto
   fator1 <- fator1 + 1
   fator2 <- 1

fimenquanto

Fimalgoritmo