Algoritmo "Lista5Questao9"
// Fazer um programa que apresente a soma dos pares de 0 até 500.
Var
// Seção de Declarações das variáveis 
cont, acum: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 2
acum <- 0
escreval("Apresentando a soma dos pares de 0 até 500.")
enquanto cont <= 500 faca
         acum <- acum + cont
         cont <- cont + 2
fimenquanto
escreva(acum)

Fimalgoritmo