Algoritmo "lista5questao5"
// Desenvolver um programa que apresente a tabuada de um número.
Var
// Seção de Declarações das variáveis 
cont, x: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 1
x <- 1
escreval("Bem-Vindo ao programa de tabuada, digite o número para começar: ")
leia(x)
enquanto (cont <= 10) faca
         escreval(x," x",cont," =", x*cont)
         cont <- cont + 1

fimenquanto

Fimalgoritmo