Algoritmo "lista44q02"
// Fazer um algoritmo que pergunte o valor atual do salário mínimo e o valor
// do salário de uma pessoa. Este algoritmo deverá exibir como resposta
// quantos salários mínimos esta pessoa ganha.

Var
// Seção de Declarações das variáveis 
min,sal: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
min <- 1300
escreva("Escreva o seu salário: R$ ")
leia(sal)
escreva("O seu salário vale por", sal/min, " salários minimos.")

Fimalgoritmo