Algoritmo "lista44q03"
// Faça um algoritmo que pergunte ao usuário um valor e exiba como resposta
// o valor com acrescimo de 18% e também o mesmo valor com desconto de 65%

Var
// Seção de Declarações das variáveis 
num: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Apresente um valor: R$ ")
leia(num)

escreval("O valor com acrescimo de 18%: R$", num + num * 0.18)
escreval("O valor com desconto de 65%: R$", num - num * 0.65 )

Fimalgoritmo