Algoritmo "lista44q06"
// Faça um algoritmo que peça um número e ao final, informe se o número
// digitado está acima 1000 ou abaixo de 1000
Var
// Seção de Declarações das variáveis 
num: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Apresente um número: ")
leia(num)
se num > 1000 entao
   escreva("O número é maior do que 1000.")
senao
     se num < 1000
        escreva("O número é menor do que 1000.")
fimse

Fimalgoritmo